### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by robertmuehsig** [VitalElement/CefGlue.Core#8]
Hi
I just found this project and wanted to try it out, unfortunately when I try to run build.ps1 I get this error:

PS D:\Code\GitHub\CefGlue.Core> .\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Error: The assembly 'Cake.Compression, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.18.0).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

When I open the sln in VS2017 eveything builds, but when I start debug it I get this:

System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Avalonia.Skia.FramebufferRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer)
   at Avalonia.Rendering.ImmediateRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

Inner Exception 1:
DllNotFoundException: Unable to load DLL 'libSkiaSharp': This operation is only valid in the context of an app container. (Exception from HRESULT: 0x8007109A)

Do I miss something?

**Comment by danwalmsley** [comment]
@robertmuehsig hey! I'm just trying to get it to build again, hopefully I can push some fixes this morning!

**Comment by danwalmsley** [comment]
@robertmuehsig just pushed a fix for bith the skia sharp exception and the cake build script.

Iv not managed to update to latest avalonia yet however! will see what I can do.

You will be interested in this app: 

https://github.com/VitalElement/Avalonia.SummerNote 

which demonstrates calling javascript, and kind of shows how it could be used to integrate html controls alongside avalonia / c# XAML controls.

**Comment by danwalmsley** [comment]
should get this
![image](https://user-images.githubusercontent.com/4672627/32368920-43bc5b80-c07f-11e7-9784-d6e3aab44d4c.png)

**Comment by danwalmsley** [comment]
@robertmuehsig ok iv updated to latest avalonia, needed a minor change to code so all working now.

I'll keep the issue open so we can keep the discussion going if you need any further help

:)

**Comment by kekekeks** [comment]
@robertmuehsig
Not sure where to contact you, so I'll leave that here.

It would be really nice to have some interop code for calling C# methods from JS hosted in CEFGlue (so it won't heavily rely on making HTTP calls). I can share some code from 2014 when we were using CEFGlue for hosting a desktop version of our web app

**Comment by gab-gil** [comment]
Hey, @danwalmsley  I wanted to know how were you able to add a web browser inside an Avalonia app. I tried using CefSharp and other dependencies but they never worked. If you could help me it would be appreciated.

**Comment by danwalmsley** [comment]
@AstralCookie  iv added a sample here:
https://github.com/VitalElement/AvaloniaWebBrowser-Sample

if you run this it will load bing.com on windows and mac

**Comment by SweetAdmin** [comment]
Hey @danwalmsley I've tried using the samples in both this project and the version you just linked and get the following error:

Unhandled Exception: System.NotSupportedException: cef_api_hash call is not supported. ---> System.DllNotFoundException: Unable to load DLL 'libcef': The specified module or one of its dependencies could not be found.

I've tried copying "Chromium Embedded Framework.frame" into the runtimes/osx/native folder with no success. Am I missing something obvious? Any advice for getting this working correctly on MacOS?

**Comment by aplocher** [comment]
@danwalmsley Thanks for the sample.  It works great in Windows, however, it depends on the .NET Framework and I can't get it to function under Linux.  Is cross platform usage possible via .NET Core?  Thanks

Here's what I get from `dotnet run` under Linux: 

```
Unhandled Exception: System.NotSupportedException: cef_api_hash call is not supported. ---> System.DllNotFoundException: Unable to load shared library 'libcef' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcef: cannot open shared object file: No such file or directory
   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   --- End of inner exception stack trace ---
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.ExecuteProcess(CefMainArgs args, CefApp application, IntPtr windowsSandboxInfo)
   at CefGlue.Avalonia.CefGlueApplicationExtensions.<>c__DisplayClass0_0`1.<ConfigureCefGlue>b__0(T b)

```

**Comment by aplocher** [comment]
@danwalmsley Thanks for your sample, it does seem to work well in Windows but I haven't been able to get it to work under Linux.  Getting the same error mentioned by @SweetAdmin 

I'm assuming it's related to this:

` <PackageReference Include="VitalElement.CefGlue.Core.Win-x64" Version="0.9.0-build30-alpha" />`

Is it possible to use CefGlue with Avalonia with other platforms besides Windows?  

Thanks

**Comment by kekekeks** [comment]
You probably need to download libcef binary and add it to LD_LIBRARY_PATH environment variable. NativeLibrary API from .NET Core 3.0 should help with resolving issues like this.

**Comment by pedrojcm** [comment]
Hi guys!

I'm having same problem on Mac. Getting CefGlue to work on Mac has been a REALLY frustrating ride as there is no GOOD information whatsoever anywhere (at least it has been proving very hard to find!)
CEF guys decided to completely change folder structure for Mac, only god knows why (it is called libcef.dll on windows, libcef.so on linux, why the blip should mac be different and have a completely different name and folder structure?? There can not be any good reasoning for this...)

Every sample I try I get different errors, I got Avalonia sample to work with an older version of cef but getting Trace/BPT trap: 5 on the latest CEF version... And be aware that I got the older versions to work by seriously hacking the built cefsimple/cefclient app bundles and with some weeks of trial and error!

In this century, these kind of processes shouldn't be this hard!

Having said that, and I'm really sorry for my frustration, does anyone have ANY clue on how to get CEFGlue and Avalonia to work on Mac and Windows? (I mean, does anyone have an "easy" step by step process to achieve such an app?)

Thank you and sorry again!
